### ISSUE TITLE
DMS MVP - Login

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-controls-react#18]
As an end user I want to be able to log in to my document management system mvp page, so I can try out the features of the app.

## Acceptance criteria:
- [ ] The user can log in when she provides her e-mail addres and password (and registered before)
- [ ] We are validating the e-mail format client-side
- [ ] Both fields are validated as required
- [ ] If either of the provided information is wrong (or the user is not registered), we display a "Wrong user name or password" error message.
- [ ] When the user clicks (or taps) on the login button, we disable it until the end of the evaluation. If the login is successful, the user finds herself at the DMS front page.

initial wireframe:
![login](https://user-images.githubusercontent.com/632613/28877268-2827a7e8-779c-11e7-8987-ce9658bfed05.png)

**Comment by herflis** [comment]
Issue moved to [SenseNet/sn-dms-demo #5](https://github.com/SenseNet/sn-dms-demo/issues/5) via [**ZenHub**](https://www.zenhub.com/)
